version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b1
  - dependency-name: typed-ast
    versions:
    - 1.4.3
  - dependency-name: idna
    versions:
    - "3.1"
  - dependency-name: google-auth
    versions:
    - 1.29.0
